//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dificuldade
    {
        public int id_dificuldade { get; set; }
        public string descricao { get; set; }
        public int nr_letras { get; set; }
    }
}
